apiVersion: v1
kind: Namespace
metadata:
  name: cashflow-app
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cashflow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: fumorin/cashflow-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://test:test123@yb-unified-tserver.yb-system.svc.cluster.local:5433/test_app" 
            - name: DB_SSL
              value: "false"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cashflow-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cashflow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: fumorin/cashflow-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend.cashflow-app.svc.cluster.local:3000"
            - name: DNS_RESOLVER
              value: "rke2-coredns-rke2-coredns.kube-system.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cashflow-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

